### ISSUE TITLE
Extension doesn't work on the latest version of VSCode

### ISSUE THREAD

**Issue by jezsung** [seivan/swipe-to-navigate#7] opened 2020-12-17 07:41 UTC
Swiping seems not working on the latest version of VSCode 1.52. I could solve the problem by downgrading VSCode to 1.51.

**Comment by tsavo-vdb-knott** [comment] 2020-12-20 00:24
I can verify this also !

**Comment by ivanph** [comment] 2021-02-02 06:51
If you are experiencing this issue, it can be fixed locally by applying the change in #8 locally.
You need to find the location of the plugin, in my case this was under `~/.vscode/extensions/seivan.swipe-to-navigate-1.0.3`.
And apply the changes on the file `swipe-to-navigate.js` under `patches`.

**Comment by kevinboosten** [comment] 2021-02-02 07:58
> If you are experiencing this issue, it can be fixed locally by applying the change in #8 locally.
> You need to find the location of the plugin, in my case this was under `~/.vscode/extensions/seivan.swipe-to-navigate-1.0.3`.
> And apply the changes on the file `swipe-to-navigate.js` under `patches`.

Ah, great! Thanks! I was missing this feature very badly 🙂.

**Comment by this-fifo** [comment] 2021-02-05 03:33
~~@ivanph I tried your suggested changes but they didn't work for me unfortunately, I am on macOS Big Sur 11.2 and vscode 1.53.0~~

EDIT:
Oh well, turns out I had a conflicting gesture on my system settings for the swipe gesture 🤦‍♂️, I can confirm that those changes now are working. Sorry! 😁

**Comment by seivan** [comment] 2021-02-10 09:14
Hey guys, sorry for not getting back earlier. 
It seems that the PR from @ivanph solves this and I'll get to push this later tonight!

**Comment by seivan** [comment] 2021-02-22 20:53
So I've deployed https://github.com/seivan/swipe-to-navigate/pull/8
It should propagate on the marketplace anytime soon. Thanks everyone for testing and @ivanph for fixing it. 

Edit: Sorry for the delay!

**Comment by seivan** [comment] 2021-02-22 20:54
Fixed in https://github.com/seivan/swipe-to-navigate/releases/tag/1.1.2

**Closed as completed by seivan** 2021-02-22 20:54 UTC
Labels: bug
